name: jss_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  feather_icons_flutter: ^4.7.4
  animated_text_kit: ^2.2.0
  animated_bottom_navigation_bar: ^0.1.2+2
  circular_reveal_animation: ^1.1.5
  bottom_animation: ^1.1.0
  carousel_slider: ^2.2.1
  fl_chart: ^0.11.1
  gradient_text: ^1.0.2
  draw_graph: ^0.0.1
  google_maps_flutter: ^0.5.32
  geolocator: ^6.0.0
  hexcolor: ^1.0.4
  step_progress_indicator: ^0.2.4+7
  timeline_tile: ^0.1.2
  date_range_picker: ^1.0.6
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - lib/assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 